### ISSUE TITLE
Как лучше всего редактировать проект?

### ISSUE THREAD

**Issue by HarismaLZT** [Dionis1902/FRT#4]
Приветствую тебя ещё раз, я хочу добавить свой функционал один в твой проект, но для меня твой проект слишком большой, не могу пока понять, а какой мне файл и в какой папке, мне нужно редактировать для того, чтобы впилить свой функционал.
если это возможно, дашь наводку?
я не буду добавлять эту функцию в PR/Fork, а просто хочу локально "пощупать".

**Comment by Dionis1902** [comment]
Все новые функции добавляются в папку functions/functions

**Comment by HarismaLZT** [comment]
Благодарю тебя за подсказку!

**Comment by HarismaLZT** [comment]
А после того, как я добавил новую функцию, мне нужно что-то далее делать? или всё "автоматически забилдиться"?

**Comment by Dionis1902** [comment]
Oн сам появится его не надо нигде добавлять, а верстается оно тоже автоматически, посмотри на коструктор в моих функциях

**Comment by HarismaLZT** [comment]
я может что-то не так сделал? у меня ничего не выходит

**Comment by HarismaLZT** [comment]
Мог бы ты объяснить, как мне унаследовать класс?
https://pastebin.com/

**Comment by Dionis1902** [comment]
Скинь на почту код, den70007.ua@gmail.com

**Comment by HarismaLZT** [comment]
момент

**Comment by HarismaLZT** [comment]
Отправил!

**Comment by Dionis1902** [comment]
Взгляни на мои функции, думаю поймешь в чем проблема
