### ISSUE TITLE
Как добавить кастомного пользователя?

### ISSUE THREAD

**Issue by HarismaLZT** [Dionis1902/FRT#6]
В каком файле я могу добавить кастомного пользователя, вместо дефолтного `root`?
Мне просто нужно вписать доп.данные сюда?
```
class Settings:
    _DATA = {
        'username': 'root',
        'password': 'roottoor',
        'flood_wait': 60
    }
```
Или неправильный синтаксис будет?

**Comment by Dionis1902** [comment]
Ты сможешь изменить это в настройках, когда запустишь
