### ISSUE TITLE
settings.py

### ISSUE THREAD

**Issue by HarismaLZT** [Dionis1902/FRT#7]
Привет, снова я, извини за это.

При добавлении нового пользователя, ничего не работает, т.е панель выдаёт ошибку о том, что пользователя не существует.
вход по root - работает, а по test - не работает.
что делаю не так? мог бы пож-а шаблон дать, правда, не понимаю.

```
class Settings:
    _DATA = {
        'root': {
            'password': 'roottoor',
            'flood_wait': 60
        },
        'test': {
            'password': 'testpassword',
            'flood_wait': 30
        }
    }
```

**Comment by Dionis1902** [comment]
Можно только 1 аккаунт
