### ISSUE TITLE
При авторизации на панель, неверный запрос HTTP.

### ISSUE THREAD

**Issue by nsvk13** [Dionis1902/FRT#8]
После того, как панель поднял, при авторизации выдаёт спам в терминале и "не безопасное подключение в браузере".

1. Скриншот с браузера - https://prnt.sc/wLz5tVuqHwZX
2. Скриншот с терминала - https://prnt.sc/xySiTMDVDH9Q

**Comment by Dionis1902** [comment]
Fixed, pull new frt image
