### ISSUE TITLE
Need a template or brief documentation

### ISSUE THREAD

**Issue by nsvk13** [Dionis1902/FRT#9]
There are two scripts.
I want to add them at least locally (fork), in a panel.
You told me about a month ago to inherit a basic function.
But I don't quite understand, what's next?
You don't need anything else at all?

Not even touch the web files? Just the python files?
Here's an example of one script I want to implement: https://pastebin.com/9F6T4U0Q.

(yes, the quality of the code is terrible, but still...)
I don't think feature inheritance alone will be enough.

Could you create a short documentation with an example? That way you could create a PR.
That would be very handy.
I realize that you probably don't care about that. I want to learn how to write and interact better in Python, so I accept practice on any open source projects.

But I don't understand the way your functions are set up.
I don't understand how I can adapt my script to a web panel.

**Comment by Dionis1902** [comment]
```
# You must add this to functions/functions with same name what __id__

from functions.base_function import Base
from functions.utils import Field, Types


class Function(Base):
    """Some description to function"""

    __id__ = 'some_unique_id'  # Example test_function
    __function_name__ = 'Some name for UI'

    def __init__(self, accounts: Field(Types.ACCOUNTS, label_name='Accounts'),  # Required for get accounts from ui
                 chats: Field(Types.INPUTS, label_name='Chats link', pattern=r'^https://t.me/(\\w{5,32}|\\+\\w+|joinchat/\\w+)$', placeholder='https://t.me/simple_chat'),  # For example generate on ui tab with INPUTS for get links
                 messages: Field(Types.TEXTAREA, label_name='Messages', placeholder='Hello world!'),  # For example generate on ui tab with TEXTAREA for get messages
                 settings: Field(Types.SETTINGS, label_name='Settings')):  # Required for get settings from ui
        super().__init__(accounts, settings)  # Required
        self._chats = chats
        self._messages = messages

    async def _run(self, client, account):  # Required this function will be called, you get client (pyrogram client) and account is Account model
        # Implement your logic here
        pass
```
Then the function will be added automatically
See https://github.com/Dionis1902/FRT/tree/master/functions/functions

**Comment by nsvk13** [comment]
Thanks.
